### ISSUE TITLE
bug of music extention

### ISSUE THREAD

**Issue by gego51** [TurboWarp/scratch-gui#33]
With a built Gui for an offline usage, the music extension block makes no more sounds 

I use Windows 10 with Edge and Firefox

**Comment by GarboMuffin** [comment]
We change the music to be loaded dynamically instead of being part of the big JS bundle in an effort to remove unnecessary bloat (music is hundreds of KB if not MB).

Download your own local copy of TurboWarp/scratch-vm (the Getting Started document should describe this) and do `git revert 047883e8ad2df411d63efd87c66d8cdcae58706a`, that should revert it.

**Comment by gego51** [comment]
ok, thanks
