### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Weredime** [TurboWarp/scratch-gui#550]
Can this be incorporated in a project as BSD-3? (this is for purposes relating to messy licensing and stuff)

**Comment by GarboMuffin** [comment]
Disclaimer: I am not a lawyer and this is not legal advice.

TurboWarp/scratch-gui is GPL 3.0 https://github.com/TurboWarp/scratch-gui/blob/develop/LICENSE.

Generally, using GPL 3.0 code in a derivative work will require all the code to be available as GPL 3.0.

Embedding an \<iframe\> of turbowarp.org's embed page probably creates an "aggregate work" rather than a "derivative work" and probably doesn't have the same virality.

Other TurboWarp repositories may be under much more permissive licenses. Many of them can be used on their own in any project, even proprietary ones.

**Comment by GarboMuffin** [comment]
If you were to elaborate a bit more, I could give you a better answer.

**Comment by Weredime** [comment]
> If you were to elaborate a bit more, I could give you a better answer.

Basically, I have a new project that uses BSD-3. It's basically Scratch but much better with new cool blocks and better moderation. I don't want to go in to the deep world of licensing (it's pretty annoying). TW VM uses BSD-3 so that's okay. But I'm doing a hard fork of turbowarp (as it has a much better maintained codebase than scratch) and scratch repos that turbowarp uses. I'd like to use the BSD-3 license with my new project, but the GPL license disallows it

**Comment by GarboMuffin** [comment]
If you want to use any part of TurboWarp/scratch-gui or ScratchAddons, you will use GPL 3.0.

**Comment by GarboMuffin** [comment]
If the license matters to you then go talk to a real lawyer. I can't help you any more than this.
